from .get_all_next_of_kin import get_all_next_of_kin
from .create_next_of_kin import create_next_of_kin
from .update_next_of_kin import update_next_of_kin
from .delete_next_of_kin import delete_next_of_kin