services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_DB: itca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itca
